# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import task2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefile', models.FileField(upload_to=task2.models.content_file_name)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
